
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  database: rails_demo_march2021_development


test:
  <<: *default
  username: postgres
  database: rails_demo_march2021_test


production:
  <<: *default
  database: rails_demo_march2021_production
  username: rails_demo_march2021
  password: <%= ENV['RAILS_DEMO_MARCH2021_DATABASE_PASSWORD'] %>
